###
### ~ Monica dev docker-compose
###
### This file is used for dev purpose.
### The standard monica image definition will be found here: https://github.com/monicahq/docker
###

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile
    image: monica:dev
    depends_on:
      - mysql
    ports:
      - 8080:80
    env_file: .env.dev
    volumes:
      - /var/www/html/storage
      - ./app:/var/www/html/app
      - ./database:/var/www/html/database
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: sekret_root_password
    restart: always
    ports:
      - 3000:80
    volumes:
      - /sessions

  mail:
    container_name: fake_mail
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
