name: Docker

on:
  push:
    branches:
      - master

jobs:
  docker-run:
    runs-on: ubuntu-latest
    name: Docker build master

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.5.0
        with:
          images: ghcr.io/monicahq/monica
          tag-sha: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: scripts/docker/Dockerfile
          context: .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
